## two dimensional matrix

In [1]:
import numpy as np
sample_matrix = np.array([[50,20,1,23],[24,23,31,40],[61,25,33,34],[56,76,24,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 31, 40],
       [61, 25, 33, 34],
       [56, 76, 24,  7]])

In [2]:
sample_matrix[2,4]

IndexError: index 4 is out of bounds for axis 1 with size 4

In [3]:
sample_matrix[1,2]

31

In [4]:
sample_matrix[2,3]

34

In [5]:
sample_matrix[1,1]

23

In [6]:
sample_matrix[2,:]

array([61, 25, 33, 34])

In [7]:
sample_matrix[2]

array([61, 25, 33, 34])

In [8]:
sample_matrix[(2,3)]

34

In [9]:
sample_matrix[(2,3),:]

array([[61, 25, 33, 34],
       [56, 76, 24,  7]])

In [10]:
sample_matrix[,:2]

SyntaxError: invalid syntax (3035909873.py, line 1)

In [11]:
sample_matrix[:2]

array([[50, 20,  1, 23],
       [24, 23, 31, 40]])

In [12]:
sample_matrix[:,2]

array([ 1, 31, 33, 24])

In [13]:
sample_matrix(:,(1,3))

SyntaxError: invalid syntax (2064567441.py, line 1)

In [14]:
sample_matrix[:,(1,3)]

array([[20, 23],
       [23, 40],
       [25, 34],
       [76,  7]])

In [15]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [16]:
np.random.rand(3,5) ## this only returns the positive random numbers between 0 and 1

array([[0.63077762, 0.86573112, 0.05414636, 0.95066495, 0.13429456],
       [0.22546373, 0.06071742, 0.66807595, 0.39384312, 0.47182296],
       [0.2241314 , 0.00449814, 0.93986029, 0.76180974, 0.94510825]])

In [17]:
np.random.randn(2,4) ## this retruns all the random numbers positive and negative between 0 and 1

array([[-1.26440552,  0.54322199, -1.20501994,  2.01201534],
       [ 1.71251379, -0.7796267 , -0.67121871, -0.23313513]])

In [28]:
np.random.randint(10,20)

11

In [34]:
np.random.randint(20,56,100)

array([51, 43, 35, 55, 52, 31, 42, 50, 54, 28, 26, 53, 36, 29, 23, 30, 42,
       32, 45, 46, 49, 49, 47, 51, 27, 37, 45, 42, 33, 20, 40, 54, 40, 40,
       37, 36, 36, 54, 33, 33, 55, 54, 34, 29, 45, 52, 28, 29, 42, 51, 43,
       51, 51, 44, 47, 49, 37, 41, 43, 41, 52, 36, 49, 39, 41, 43, 33, 43,
       37, 49, 52, 37, 27, 26, 54, 44, 33, 51, 25, 46, 48, 31, 53, 34, 48,
       21, 52, 36, 52, 32, 29, 47, 48, 25, 53, 48, 51, 26, 34, 46])

In [43]:
sample_array = np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [42]:
rand_array = np.random.randint(0,100,20)
rand_array

array([42, 43, 45, 82, 37, 22, 12, 98, 84, 20, 67, 40,  7, 97, 12,  4, 37,
       69, 99, 51])

In [44]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [45]:
sample_array.reshape(15,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [46]:
sample_array(4,3)

TypeError: 'numpy.ndarray' object is not callable

In [47]:
sample_array.reshape(4,3)

ValueError: cannot reshape array of size 30 into shape (4,3)

In [48]:
rand_array.max()

99

In [49]:
rand_array.min()

4

In [50]:
rand_array.argmax()

18

In [51]:
rand_array.argmin()

15

In [52]:
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [54]:
a = np.random.rand(2,3)
a

array([[0.65550928, 0.42368733, 0.31898337],
       [0.38552593, 0.86082628, 0.30808589]])

In [55]:
a.T

array([[0.65550928, 0.38552593],
       [0.42368733, 0.86082628],
       [0.31898337, 0.30808589]])

In [57]:
sample_array = np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [58]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [59]:
sample_array+rand_array

ValueError: operands could not be broadcast together with shapes (19,) (20,) 

In [60]:
np.exp(sample_array) ## it retruns the exponential values.

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [61]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [66]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [67]:
np.sqaure(sample_array)

AttributeError: module 'numpy' has no attribute 'sqaure'

In [68]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [69]:
np.std(sample_array)

5.477225575051661

In [70]:
np.var(sample_array)

30.0

In [71]:
np.mean(sample_array)

10.0

In [72]:
np.round(sample_array,decimals=2)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [74]:
sport = np.array(['golf','cricket','fball','cricket']) ## the unique() considers the repeatitive value in the array only once.
np.unique(sport)

array(['cricket', 'fball', 'golf'], dtype='<U7')